spring:
  application:
    name: lanaseq
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;IGNORECASE=TRUE;MODE=MYSQL
    username: sa
    password:
    tomcat:
      test-on-borrow: true
      validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        '[enable_lazy_load_no_trans]': true
  mail:
    host: myemailserver.com
  servlet:
    multipart:
      enabled: false

app:
  home:
    folder: ${user.home}/lanaseq
    windows-label: '\\lanaseq01\lanaseq'
    unix-label: 'smb://lanaseq01/lanaseq'
  sample-folder: sample
  dataset-folder: dataset
  analysis:
    folder: ${app.home.folder}/analysis
    windows-label: '${app.home.windows-label}\analysis'
    unix-label: '${app.home.unix-label}/analysis'
  analysis-delete-age: PT48H
  analysis-symlinks: false
  upload:
    folder: ${app.home.folder}/upload
    windows-label: '${app.home.windows-label}\upload'
    unix-label: '${app.home.unix-label}/upload'
  upload-delete-age: PT6H
  serverUrl: http://localhost:8080

security:
  lockAttemps: 5
  lock-duration: PT3M
  disableSignAttemps: 20

ldap:
  enabled: false
  id-attribute: uid
  mail-attribute: mail

# Web server.
server:
  port: 8080
  servlet:
    session:
      persistent: false
  forward-headers-strategy: native

vaadin:
  productionMode: false
  closeIdleSessions: true
  license:
    assume: false
    paths:
      - '${user.home}/.vaadin/offlineKey'
      - '${user.home}/.vaadin/proKey'
      - '${user.home}/.vaadin/userKey'

mail:
  enabled: true
  from: lanaseq@ircm.qc.ca
  to: christian.poitras@ircm.qc.ca
  subject: ${spring.application.name}

logging:
  file:
    name: ${spring.application.name}.log

---
spring:
  config:
    activate:
      on-profile: test
  ldap:
    embedded:
      base-dn: dc=mycompany,dc=com
      credential:
        username: uid=poitrasc
        password: secret
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  mail:
    host: localhost

app:
  archives:
    - folder: ${app.home.folder}/archives
      windows-label: '${app.home.windows-label}\archives'
      unix-label: '${app.home.unix-label}/archives'
    - folder: ${user.home}/lanaseq2/archives2
      windows-label: '\\lanaseq02\lanaseq\archives2'
      unix-label: 'smb://lanaseq02/lanaseq/archives2'

security:
  rememberMeKey: 'JfYMi0qUQVt8FObsZHW7'

ldap:
  enabled: true
  object-class: person

vaadin:
  productionMode: false

logging:
  file:
    name: test.log

---
spring:
  config:
    activate:
      on-profile: integration-test
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

app:
  archives:
    - folder: ${app.home.folder}/archives
      windows-label: '${app.home.windows-label}\archives'
      unix-label: '${app.home.unix-label}/archives'
  serverUrl: http://localhost:${local.server.port}

security:
  rememberMeKey: 'JfYMi0qUQVt8FObsZHW7'

vaadin:
  productionMode: false

mail:
  enabled: false

logging:
  file:
    name: test.log

download-home: ${user.dir}/target/download

---
spring:
  config:
    activate:
      on-profile: context-path

server:
  servlet:
    context-path: /lanaseq-test
