CREATE TABLE IF NOT EXISTS users (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  email varchar(255) NOT NULL,
  name varchar(255),
  hashed_password varchar(255),
  sign_attempts int NOT NULL DEFAULT 0,
  last_sign_attempt timestamp,
  active boolean NOT NULL DEFAULT 0,
  manager boolean NOT NULL DEFAULT 0,
  admin boolean NOT NULL DEFAULT 0,
  expired_password boolean NOT NULL DEFAULT 0,
  locale varchar(255),
  creation_date timestamp NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (email)
);
CREATE TABLE IF NOT EXISTS forgot_password (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  request_moment timestamp NOT NULL,
  confirm_number varchar(100) NOT NULL,
  used boolean NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  CONSTRAINT forgotpasswordUser_ibfk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS protocol (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL,
  owner_id bigint NOT NULL,
  creation_date timestamp NOT NULL,
  note clob,
  PRIMARY KEY (id),
  CONSTRAINT protocolOwner_ibfk FOREIGN KEY (owner_id) REFERENCES users (id) ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS protocol_file (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  protocol_id bigint DEFAULT NULL,
  filename varchar(255) NOT NULL,
  content blob,
  deleted boolean NOT NULL DEFAULT 0,
  creation_date timestamp NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT protocolfileProtocol_ibfk FOREIGN KEY (protocol_id) REFERENCES protocol (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS dataset (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL,
  experiment_date DATE NOT NULL,
  owner_id bigint NOT NULL,
  editable boolean NOT NULL DEFAULT 0,
  creation_date timestamp NOT NULL,
  note clob,
  PRIMARY KEY (id),
  UNIQUE (name),
  CONSTRAINT datasetOwner_ibfk FOREIGN KEY (owner_id) REFERENCES users (id) ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS sample (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL,
  sample_id varchar(255) NOT NULL,
  replicate varchar(255),
  assay varchar(255) NOT NULL,
  type varchar(255),
  target varchar(255),
  strain varchar(255) NOT NULL,
  strain_description varchar(255),
  treatment varchar(255),
  experiment_date DATE NOT NULL,
  protocol_id bigint NOT NULL,
  owner_id bigint NOT NULL,
  editable boolean NOT NULL DEFAULT 0,
  creation_date timestamp NOT NULL,
  note clob,
  PRIMARY KEY (id),
  UNIQUE (name),
  CONSTRAINT sampleOwner_ibfk FOREIGN KEY (owner_id) REFERENCES users (id) ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS dataset_samples (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  dataset_id bigint NOT NULL,
  samples_order int,
  samples_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT datasetSamplesDataset_ibfk FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT datasetSamplesSample_ibfk FOREIGN KEY (samples_id) REFERENCES sample (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS dataset_keywords (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  dataset_id bigint NOT NULL,
  keywords varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT datasetKeywordsDataset_ibfk FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS dataset_filenames (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  dataset_id bigint NOT NULL,
  filenames varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT datasetFilenamesDataset_ibfk FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS sample_keywords (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sample_id bigint NOT NULL,
  keywords varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sampleKeywordsSample_ibfk FOREIGN KEY (sample_id) REFERENCES sample (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS sample_filenames (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sample_id bigint NOT NULL,
  filenames varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sampleFilenamesSample_ibfk FOREIGN KEY (sample_id) REFERENCES sample (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE sample_public_file (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  sample_id bigint(20) NOT NULL,
  path varchar(255) NOT NULL,
  expiry_date DATE NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT samplePublicFile_ibfk FOREIGN KEY (sample_id) REFERENCES sample (id) ON DELETE CASCADE ON UPDATE CASCADE
);
